// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdzyqryldulesnmxuzoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkenlxcnlsZHVsZXNubXh1em96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDQyNDUsImV4cCI6MjA2MDc4MDI0NX0.a9Q8fcEayiRcHkPnTZiD1AQcNya9E6n_91ciPg5pQdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);